name: Test1  # Name of the Catalog Entry
description: Test Desription|
  # Description of the Catalog Entry
version: 1 # Version of the Catalog to be used
category: Test# Category to be used for searching catalog entries
maintainer:  Emil Langazov # The maintainer of the catalog entry
license: No # The license
projectURL: # A URL related to the catalog entry
